# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hf-api-diego-arciniegas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        env:
          PREFIX: ${{ vars.PREFIX }}
          PORT: ${{ vars.PORT }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PORT: ${{ vars.SQL_PORT }}
          SQL_PASS: ${{ secrets.SQL_PASS }}
          SQL_DB: ${{ vars.SQL_DB }}
          SQL_HOST: ${{ vars.SQL_HOST }}
          JWT_SECRET: ${{ vars.JWT_SECRET }}
          REFRESH_SECRET: ${{ vars.REFRESH_SECRET }}
          EXPIRE_TOKEN: ${{ vars.EXPIRE_TOKEN }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_57588DCDA00C4392A266772C0A1081B6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B4E33F70DC78443BA3349C2E7A17E3A7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_41B84A5E770C44F688A2622FF3A62A8B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hf-api-diego-arciniegas'
          slot-name: 'Production'
          package: .
          